### ISSUE TITLE
Changes to developer token page on Hypothesis

### ISSUE THREAD

**Issue by robertknight** [haritzmedina/highlightAndGo#42]
Hello,

I would like to advise you about changes to the developer token page in Hypothesis which may affect this project.

Hypothesis received a very large number of requests for https://hypothes.is/account/developer over the last 24 hours. We don't have much information about the source but the requests appear to be from an automated script or tool running inside a recent version of Chrome. All of the automated requests were failing with 404 (not logged in) or 429 (rate limited) errors. To protect our systems we have deployed an automated browser check for this page intended to prevent scraping by bots.

The developer token page is only intended to be used by humans directly. Third-party clients for Hypothesis should really [use OAuth](https://h.readthedocs.io/en/latest/api/authorization/). This is more complex to set up, but there is code [in the Hypothesis client](https://github.com/hypothesis/client/blob/master/src/sidebar/util/oauth-client.js) which may be of use. For scripts/tools created for personal use you can still use a developer token for API access but it will have to be copied and pasted manually by the user rather than scraped automatically.

**Comment by haritzmedina** [comment]
Hello @robertknight ,

First of all thanks for notifying me about this issue. I don't really know whether some of these large number of calls could come from any of our extensions or not. We didn't change the implementation of how users are logged in Hypothes.is in the last months. However, I remember that I've been trying to integrate the oauth client in our Hypothes.is clients, but it wasn't successful. There is still an active the issue to solve this in other of my repositories

I've been looking [our implementation for Hypothes.is oauth](https://github.com/haritzmedina/reviewAndGo/commit/f55dd07f08ac7bb4c6a9c8e81a8eb3b0ddfec4b9), but in my case it seems that the callback it is not working anymore in any of my clients, so alternatively we use also the scraping method for logins. The error I found is the following:

After the user authorize Highlight&Go to access the extension.
![image](https://user-images.githubusercontent.com/6429012/99875802-a24d7f80-2bf2-11eb-85d8-b1a2f27fba92.png)

The page stucks in a blank page:
![image](https://user-images.githubusercontent.com/6429012/99875470-3c5ff880-2bf0-11eb-94e0-f6c8e4987ea4.png)

And the error that appears in the console is the following:
![image](https://user-images.githubusercontent.com/6429012/99875404-b93ea280-2bef-11eb-828d-de053f85420c.png)

The error must be related with the origins of our clients, notifying that the origin doesn't exist (what is true as the protocol, and the full URL doesn't appear to be correct).
`chrome-extensions://bihmalipgnlomidlpekdnoohiejppfmo`

It should be a URL of my extension (for the case of Highlight&Go something like):
`chrome-extension://bihmalipgnlomidlpekdnoohiejppfmo/pages/hypothesisOAuth.html`

As developers, we don't have access to [manage our oauth clients in Hypothes.is](https://github.com/hypothesis/product-backlog/issues/376), can you check if the clients are still active, which ones are the origins of my clients and set them to a proper URL like above with their corresponding extension ID?

| Name | client id | chrome extension ID |
|----------|:-------------:|------:|
| DScaffolding | 9a63814a-7e36-11e9-ac44-0fa8228afeea | hkgmnnjalpmapogadekngkgbbgdjlnne |
| Highlight&Go | bea89e64-7e36-11e9-a6ab-134f99967cf3 | bihmalipgnlomidlpekdnoohiejppfmo |
| Mark&Go | f2905a32-7e36-11e9-bc75-df9de7e811fb | kjedcndgienemldgjpjjnhjdhfoaocfa |
| Review&Go | 120a1f06-7e37-11e9-bbe0-c3e92559eab1 | hgiannlbfceoomjmcgedbmkfeblbcogi |

Thank you in advance.

**Comment by robertknight** [comment]
Hello @haritzmedina,

Those OAuth clients all exist, but you're right that the protocol was incorrect. I've corrected them from `chrome-extensions://` to `chrome-extension://`. If you are using the `postMessage` method of returning an access token then only the origin matters (`chrome-extension://<ID>` in this case), the path does not. If you were to switch to the redirect method for any reason then we would need to update the path.

**Comment by haritzmedina** [comment]
Thanks for your fast reply @robertknight ! Now it seems to be working like a charm. Probably the problem was simply the bad protocol name when redirecting after user authentication. I'm just simply using the `postMessage` method, so leave the origin as it is right now.

I have already publish in Chrome Store the patched version for Highlight&Go (it should be updated in the following days) and I will do exactly the same for the rest of the extensions as well, but it seems to be quite straightforward. Still, I have to check whether the client ids for the rest of the extensions are working well too, but in case I need further help I will contact you again via reopening this issue.

Thanks for helping me to solve the problem, and in case of any other problem, please let me know.

**Comment by robertknight** [comment]
This is a great - thanks for the quick response @haritzmedina!
